import rimraf from 'rimraf';
import path from 'path';
import { ELECTIONS_DIR } from '../../global';
import createElection from '../createElection';

describe('Tests createElection', () => {
  it('Should return an election id', (done) => {
    function callback(data) {
      try {
        expect(data).toBeDefined();
        expect(data.status).toEqual('OK');
        expect(data.payload).toBeDefined();
        // Clear data generated by this test.
        rimraf.sync(path.join(ELECTIONS_DIR, data.payload));
        done();
      } catch (error) {
        done(error);
      }
    }
    createElection(callback);
  });
});
